spring.application.name=server

spring.datasource.url=jdbc:mysql://localhost:3306/zenve?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Krish@2503
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.cors.allowed-origins=http://localhost:5173,http://localhost:5174

app.jwt.secret=Q76oXAoX4wTWyMm29wMD2bj9c9Ir59CjZxhV1c5ny3O
app.jwt.expiration-ms=86400000

app.seed.user.email=murthyk011@gmail.com
app.seed.user.password=murthy@123
app.seed.user.name=murthy
